[versions]
jakarta-annotation = "3.0.0"
junit-jupiter = "5.10.3"
kotlin-jvm = "2.0.21"
mockk = "1.13.13"

[libraries]
jakarta-annotation = { module = "jakarta.annotation:jakarta.annotation-api", version.ref = "jakarta-annotation" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit-jupiter" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

[plugins]
kotlin-jvm  = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }