@startuml
class CLIInterpreter {
    - Environment environment
    - CommandsParser parser
    + run()
}

class CommandsParser {
    + parse(String input): List<Command>
}

class Environment {
    + setVariable(String name, String value)
    + getVariable(String name): String
    + getWorkingDirectory(): String
    + setWorkingDirectory(String newDirectory)
}

interface Command {
    + execute(Environment environment, InputStream input, OutputStream output, List<String> args): void
}

class EchoCommand

class CatCommand

class WcCommand

class PwdCommand

class ExitCommand

class GrepCommand

CLIInterpreter --> CommandsParser
CLIInterpreter --> Environment
CommandsParser --> Command
Command <|-- EchoCommand
Command <|-- CatCommand
Command <|-- WcCommand
Command <|-- PwdCommand
Command <|-- ExitCommand
Command <|-- GrepCommand

@enduml
