@startuml
start
:Получаем строку ввода;
:Токенизируем строку (учитываем кавычки, пайплайны, переменные окружения);
:Разбираем токены;
if (Есть подстановки переменных окружения?) then (да)
  :Подставляем значения переменных окружения;
  while (Остались подстановки?) is (да)
    :Повторная подстановка значений;
  endwhile
else (нет)
  :Используем токен как есть;
endif
if (Есть пайплайны?) then (да)
  :Разделяем строку на команды;
  :Создаем цепочку команд;
else (нет)
  :Создаем одну команду;
endif
:Возвращаем объект(ы) Command;
stop
@enduml
