@startuml
actor Пользователь
participant CLIInterpreter
participant commandsParser
participant Environment
participant CommandRegistry
participant Command
participant ExternalProcess

Пользователь -> CLIInterpreter: Ввод команды
CLIInterpreter -> commandsParser: parse(environment, input) парсинг команды
commandsParser -> commandsParser: Парсинг команды
commandsParser -> CommandRegistry: Получить Command для команды
CommandRegistry --> commandsParser: Возвращает соответствующий Command объект
commandsParser -> CLIInterpreter: Возвращает список Command объектов

CLIInterpreter -> Command: execute(environment, input, output, args) выполнение команды
alt Встроенная команда
    Command --> Command: Выполнение логики команды
    Command --> CLIInterpreter: Возврат результата
else Внешняя команда
    Command -> ExternalProcess: Запуск процесса
    ExternalProcess --> Command: Возврат результата
    Command --> CLIInterpreter: Возврат результата
end

CLIInterpreter -> Пользователь: Вывод результата

note right of CLIInterpreter: Если пайплайн, то повторить execute для каждой команды в цепочке
@enduml
